name: Cypress Parallel Tests with Cypress Cloud

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3] # Adjust this number to match your desired parallelization level
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build --no-cache -t cypress-cloud-image .

    - name: Run Cypress tests in parallel with Cypress Cloud
      run: |
        docker run \
          -e CI_BUILD_ID=${{ github.run_id }} \
          -e SPLIT_INDEX=${{ strategy.job-index }} \
          -e CYPRESS_RECORD_KEY=${{ secrets.CYPRESS_RECORD_KEY }} \
          cypress-cloud-image

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: cypress-results
        path: |
          cypress/reports
          cypress/screenshots
          cypress/videos
        if-no-files-found: ignore

  publish-results:
    needs: cypress-tests
    runs-on: ubuntu-latest
    if: always()
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download test results
      uses: actions/download-artifact@v4
      with:
        name: cypress-results
        path: ./cypress-results

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./cypress-results/cypress/reports
        keep_files: true